# fly.toml app configuration file generated for datingapp-main on 2023-12-27T16:48:30-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "datingapp-main"
primary_region = "iad"

[experimental]
  auto_rollback = true

[build]
  image = "thomas7254/datingapp:latest"

[env]
  ASPNETCORE_URLS = "http://+:8080"
  CloudinarySettings__ApiKey = "474922549591869"
  CloudinarySettings__CloudName = "dtm6vdbf7"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
